### PR TITLE
Update all dependencies

### LINKED ISSUE #16: Update dependencies
Today we use this dependencies:

```
"devDependencies": {
    "electron-prebuilt": "^0.37.4",
    "google-closure-compiler-js": "^20160828.0.1",
    "gulp": "^3.9.1",
    "gulp-clean": "^0.3.2",
    "gulp-minify-css": "^1.2.4",
    "gulp-rename": "^1.2.2",
    "jshint": "^2.9.3",
    "vinyl": "^1.2.0" // 2.2.0
  },
  "dependencies": {
    "node-notifier": "^4.6.1" // 5.2.1
}
```

We can update almost all of them
We can update almost all of them, but it's important to keep our project "safe" (tip: [npm audit](https://docs.npmjs.com/cli/audit)) :)

I suggest to update for this versions:

`gulp-clean: 0.4.0`
`gulp-minify-css: ? // This package has been deprecated`
`gulp-rename: 1.4.0`
`jshint: 2.9.6`
`vinyl: 2.2.0`

> For other dependencies can use [`NCU`](https://github.com/tjunnone/npm-check-updates) package to verify this.

### PR DESCRIPTION
**Pull request by rjbeers**
* Swap out closure compiler for Babel
* Fix sourcemaps for JS and CSS
* Remove unused devDependencies

Fixes #16.

~I'm not familiar with Electron, but I'm 99.999% sure you should have electron in your dependencies, not devDependencies.~ I plan on continuing to review this repository, because I figure this is a good place for me to learn about Electron. I also see Vue is pulled from CDN, I'm sure there is opportunity to convert the gulp stuff to Webpack.

### CODE REVIEW

**Comment by ftonato** [comment]
Hello @r33beers, how are you?

How can see on the official site ~ https://electronjs.org/, the electron is a `devDependencies` because it generate a code ~without itself~...

I will update this project, accept your contributions and add new features (you can see the [issues page](https://github.com/ftonato/pomodoro-app/issues)).

If you have interesting in contribute to this project, please, go ahead and I will help you to understand about Electron :)

**Comment by rjbeers** [comment]
I've rebased after the ESLint merge. Feel free to review this one.

**Comment by ftonato** [comment]
Hello @r33beers, thanks for this PR!

Please, consider to run `npm audit` to see the possible mistakes (vulnerable packages). It's important to keep our project safe, for fix this, please run `npm audit fix --force` and again `npm audit`, you will able can see this message:

> found 0 vulnerabilities

So, do a new commit, (possible `-m 'fix: npm audit'`), and i will accept this PR.

Best regards,

**Comment by rjbeers** [comment]
@ftonato if I run that command, it will inject new major versions of dependencies into our node_modules tree, which your direct dependencies are not requesting and may not be compatible with. I do not recommend doing this.

Luckily, today, Electron released a patch fix that fixes most of the issues. The remaining issues are with `gulp` relying on `vinyl-fs` and that module having vastly out of date dependencies.

**Comment by rjbeers** [comment]
Note: `gulp@next` (v4.0.0) appears to resolve the dependency issues, but it would require converting the gulp scripts to their new format.

**Pull request merged**
